//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fine_generated
    {
        public int FineId { get; set; }
        public string BookName { get; set; }
        public Nullable<int> Fine_Charged { get; set; }
        public string Dateofissue { get; set; }
        public string Dateofreturn { get; set; }
        public string Original_Dateofreturn { get; set; }
    }
}
