//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication11.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryManagemntsystemEntities3 : DbContext
    {
        public LibraryManagemntsystemEntities3()
            : base("name=LibraryManagemntsystemEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookReturn> BookReturns { get; set; }
        public virtual DbSet<My_Book_Rating> My_Book_Ratings { get; set; }
        public virtual DbSet<MyCart> MyCarts { get; set; }
        public virtual DbSet<NewBookCollection> NewBookCollections { get; set; }
        public virtual DbSet<Purchase_History> Purchase_Histories { get; set; }
        public virtual DbSet<StudentLogin> StudentLogins { get; set; }
        public virtual DbSet<Fine_generated> Fine_generated { get; set; }
    }
}
